name: Create and Push Git Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to create (e.g., 1.0.0 or v1.0.0)'
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ensures full history and tag visibility

      - name: Create and push Git tag
        env:
          GH_TAP: ${{ secrets.GH_TAP }}
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "ðŸ”– Creating tag: $VERSION"

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git tag "$VERSION"
          git push "https://x-access-token:${GH_TAP}@github.com/${{ github.repository }}" "$VERSION"